=== thomascazaubon/projetXML/Exp/parcelle.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- RESTE A FAIRE LES ACTIVITES AGRI ET DE TRAITEMENT-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="Gestion" type="gestionType"/>
	
	<xs:complexType name="gestionType">
		<xs:sequence>
		 	<xs:element name="Parcelles" type="ParcellesType"/>
			<xs:element name="Gestionnaires" type="GestionnairesType" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="ParcellesType">
		<xs:sequence>
			<xs:element name="Parcelle" type="ParcelleType"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="ParcelleType">
			<xs:sequence>
				<xs:element name="section" type="xs:string"/>
				<xs:element name="superficie" type="xs:string"/>
				<xs:element name="Gestionnaire" type="xs:token">	
				<xs:keyref name="GestRef" refer="GestKey">
					<xs:selector xpath="Parcelle"/>
					<xs:field xpath="Gestionnaire"/>
				</xs:keyref>
				</xs:element>
				<xs:element name="Activites" type="ActiviteType"/>
			</xs:sequence>
			<xs:attribute name="numParcelle" type="xs:string" use="required"/>
	</xs:complexType>

	<xs:complexType name="GestionnairesType">
		<xs:sequence>
			<xs:element name="Gestionnaire" type="GestionnaireType">
			<xs:key name="GestKey">
				<xs:selector xpath="Gestionnaire"/>
				<xs:field xpath="@idGestionnaire"/>
			</xs:key>
			</xs:element>
		</xs:sequence>
		
	</xs:complexType>
		
	<xs:complexType name="GestionnaireType">
			<xs:sequence>
				<xs:element name="nom" type="xs:string"/>
				<xs:element name="prenom" type="xs:string"/>
				<xs:element name="adresse" type="xs:string"/>
			</xs:sequence>
			<xs:attribute name="idGestionnaire" type="xs:token"/>
	</xs:complexType>

	<xs:complexType name="ActiviteType">
		<xs:sequence>
			<xs:element name="ActAgricole" type="ActAgricoleType"/>
			<xs:element name="ActTraitement" type="ActTraitementType"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="ActAgricoleType">
		<xs:sequence maxOccurs="unbounded">
			<xs:element name="Semaine" type="xs:integer"/>
		</xs:sequence>
		<xs:attribute name="type" type="ActAgricoleTypeAccepted"/>
		<xs:attribute name="cout" type="xs:integer"/>
	</xs:complexType>

	<xs:complexType name="ActTraitementType">
		<xs:sequence maxOccurs="unbounded">
			<xs:element name="Semaine" type="xs:integer"/>
		</xs:sequence>
		<xs:attribute name="type" type="ActAgricoleTypeAccepted"/>
		<xs:attribute name="cout" type="xs:integer"/>
		<xs:attribute name="typeInsectes" type="xs:string"/>
	</xs:complexType>

	<xs:simpleType name="ActAgricoleTypeAccepted">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Anti-Insectes"/>                  
			<xs:enumeration value="RÃ©colte"/>
		</xs:restriction>
	</xs:simpleType>

</xs:schema>

=== thomascazaubon/projetXML/Exp/parcelle.xml
<?xml version="1.0" encoding="UTF-8"?>
<Gestion xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="parcelle.xsd">

<!--
Un seul élément Parcelles et un seul éléments Gestionnaires
-->
<!-- Les éléments Parcelles et Gestionnaires peuvent être dans n'importe quel ordre
-->
<Parcelles>
	<!--un ensemble non vide d'éléments Parcelle --><!--l'attribut numParcelle est une clé -->
	<!--L'utilisation de ID n'est pas acceptée -->
	<Parcelle numParcelle="P1">
		<!--
		un élément Section, un élément Superficie, un élément Gestionnaire 
		-->
		<section>parcelleSud</section>
		<superficie>1250m2</superficie>
		<!-- l'élément Gestionnaire est une référence vers l'attribut idGestionnaire de l'élément Gestionnaire -->
		<!--L'utilisation de IDREF n'est pas acceptée -->
		<Gestionnaire>G1</Gestionnaire>
		<!-- Zéro ou un élément Activites-->
		<Activites>
			<!-- Zéro ou plusieurs éléments ActAgricole-->
			<!--
			 La valeur de l'attribut type doit être soit Récolte ou Anti-insectes 
			-->
			<ActAgricole type="Récolte" cout="2500">
				<!--un ensemble non vide d'éléments Semaine -->
				<Semaine> 3 </Semaine>
				<Semaine> 5 </Semaine>
			</ActAgricole>
			<!-- Zéro ou plusieurs éléments ActTraitement
			L'élément ActTraitement est une extension de ActAgricole 
			-->
			<ActTraitement type="Anti-Insectes" cout="1800" typeInsectes="Ver">
				<Semaine> 2 </Semaine>
				<Semaine> 6 </Semaine>
			</ActTraitement>
		</Activites>
	</Parcelle>
</Parcelles>
<Gestionnaires>
	<!--un ensemble non vide d'éléments Gestionnaire 
	idGestionnaire est une clé-->
	<Gestionnaire idGestionnaire="G1">
		<nom>Godart</nom>
		<prenom>Jean</prenom>
		<adresse>Toulouse</adresse>
	</Gestionnaire>
</Gestionnaires>
</Gestion>
